iss/bids/urls.py
from django.urls import path

from iss.bids import views

app_name = "bids"

urlpatterns = [
    path("list/", views.item_list_view, name="item_list"),
    path("mylist/", views.myitem_list_view, name="item_mylist"),
    path("detail/<str:pk>/", views.item_detail_view, name="item_detail"),
    path("myitemdetail/<str:pk>/", views.myitem_detail_view, name="my_item_detail"),
    path("add/", views.item_create_view, name="item_add"),
    path("update/<str:pk>/", views.item_update_view, name="item_update"),
    path("delete/<str:pk>/", views.item_delete_view, name="item_delete"),
    path("bid_list/<str:pk>/", views.bid_list_view, name="bid_list"),
    path("bid_detail/<str:pk>/", views.bid_detail_view, name="bid_detail"),
    path("bid_add/<str:pk>/", views.bid_create_view, name="bid_add"),
    path("bid_update/<str:pk>/", views.bid_update_view, name="bid_update"),
    path("bid_delete/<str:pk>/", views.bid_delete_view, name="bid_delete"),
]

iss/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("users/", include("iss.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("items/", include("iss.bids.urls", namespace="items")),
    path("chat/", include("iss.chat.urls", namespace="chat")),
]

iss/bids/models.py
from django.db import models
from django.contrib.auth import get_user_model


class AuctionedItem(models.Model):
    name = models.TextField(null=False, blank=False, help_text="numele obiectului")
    description = models.TextField(
        null=False, blank=False, help_text="descrierea obiectului"
    )
    seller = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        help_text="cine pune la licitatie obiectul",
    )
    amount = models.DecimalField(
        max_digits=6, decimal_places=2, help_text="pretul curent al licitatiei"
    )
    start_date = models.DateTimeField(help_text="data cand incepe licitatia")
    end_date = models.DateTimeField(help_text="data cand se termina licitatia")


class Bid(models.Model):
    bidder = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        help_text="Enter the amount you wish to bid",
    )
    item = models.ForeignKey(
        AuctionedItem,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        help_text="licitatia",
    )
    amount = models.DecimalField(max_digits=6, decimal_places=2, help_text="cat ofera")

iss/bids/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView

from iss.bids.models import Bid, AuctionedItem
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import get_object_or_404
from django.db.models import Q


class ItemDetailView(DetailView):
    model = AuctionedItem
    context_object_name = "item"
    template_name = "items/item_detail.html"
    slug_field = "item"
    slug_url_kwarg = "item_id"


item_detail_view = ItemDetailView.as_view()




class MyItemDetailView(DetailView):
    model = AuctionedItem
    context_object_name = "item"
    template_name = "items/item_myitems.html"
    slug_field = "item"
    slug_url_kwarg = "item_id"


myitem_detail_view = MyItemDetailView.as_view()

class ItemListView(ListView):
    model = AuctionedItem
    paginate_by = 10
    context_object_name = "item_list"
    template_name = "items/item_list.html"

    def get_queryset(self):
        return AuctionedItem.objects.filter(~Q(seller=self.request.user))


item_list_view = ItemListView.as_view()


class MyItemListView(ListView):
    model = AuctionedItem
    paginate_by = 10
    context_object_name = "item_list"
    template_name = "items/item_mylist.html"

    def get_queryset(self):
        return AuctionedItem.objects.filter(seller=self.request.user)

myitem_list_view = MyItemListView.as_view()


class ItemCreateView(CreateView):
    model = AuctionedItem
    fields = ["name", "description", "amount", "start_date", "end_date"]
    template_name = "items/item_form.html"
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.seller = self.request.user
        return super().form_valid(form)


item_create_view = ItemCreateView.as_view()


class ItemUpdateView(UpdateView):
    model = AuctionedItem
    fields = ["name", "description", "amount", "start_date", "end_date"]
    template_name = "items/item_form.html"
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.seller = self.request.user
        return super().form_valid(form)


item_update_view = ItemUpdateView.as_view()


class ItemDeleteView(DeleteView):
    model = AuctionedItem
    template_name = "items/item_form.html"
    success_url = reverse_lazy("home")


item_delete_view = ItemDeleteView.as_view()


class BidDetailView(DetailView):
    model = Bid
    template_name = "bids/bid_detail.html"
    slug_field = "bid"
    slug_url_kwarg = "bid_id"


bid_detail_view = BidDetailView.as_view()


class BidListView(ListView):
    paginate_by = 10
    context_object_name = "bid_list"
    template_name = "bids/bid_list.html"

    def get_queryset(self):
        return Bid.objects.filter(item__pk=self.kwargs["pk"])


bid_list_view = BidListView.as_view()


class BidCreateView(CreateView):
    model = Bid


    # 'bidder' and 'item' should be filled automatically
    fields = ["amount"]
    template_name = "bids/bid_form.html"
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.seller = self.request.user
        form.instance.bidder = self.request.user
        form.instance.item = AuctionedItem.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)


bid_create_view = BidCreateView.as_view()


class BidUpdateView(UpdateView):
    model = Bid

    # 'bidder' and 'item' should be filled automatically
    fields = ["amount"]
    template_name = "bids/bid_form.html"
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.bidder = self.request.user
        form.instance.item = AuctionedItem.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)


bid_update_view = BidUpdateView.as_view()


class BidDeleteView(DeleteView):
    model = Bid
    template_name = "bids/bid_form.html"
    success_url = reverse_lazy("home")


bid_delete_view = BidDeleteView.as_view()

templates/bids/bid_delete_confirm.html
{% extends "base.html" %}
{% load static %}

{% block title %}Article {% endblock %}

{% block content %}

    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete {{ object }}. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-link"
                    type="button" value="Cancel"
                    onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
            </form>
        </div>
    </div>

{% endblock content %}

templates/bids/bid_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Licitatie{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<body>
<br><br><br>


<div class="hero-text-bid">
    <h1 style="font-size:50px">Bid Details</h1>
  </div>

<div class="card">
    <h1>{{ bid.item.name }}</h1>
    <hr>
    <h3>Price: {{ bid.amount }}$</h3>
    <h3>Bidder Name: {{ bid.bidder.name }} <br>{{ bid.bidder.username }}
    </h3>
   
    <div> <h3>Actions:</h3></div>
    <hr>
    <a  class="btn custom-btn" href="{% url 'items:item_detail' bid.item.id %}">Item page</a>
    <hr>
    <a class="btn custom-btn" href="{% url 'items:bid_update' bid.id  %}">Edit bid</a>
    <hr>
    <a class ="btn custom-btn"href="{% url 'items:bid_delete' bid.id  %}" style="background-color: red;">Delete bid</a>
  </div>




</body>
</html>

{% endblock content %}

templates/bids/bid_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}Bid {% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
    <body>
        
        
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            
            <input class="btn btn-success" type="submit" value="Save">
            
        </form>
    </body>
</html>

{% endblock content %}

templates/bids/bid_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Licitatie{% endblock %}

{% block content %}

<h1>Currently placed bids  </h1>



<div class="content">
    
        <div class="container">
    
          <div class="table-responsive">
    
            <table class="table table-striped custom-table">
              <thead>
                <tr>
                  
                  <th scope="col">Bidder name</th>
                  <th scope="col">Item</th>
                  <th scope="col">Bid Amount</th>
                  <th scope="col">Bid Details</th>
                  <th scope="col">Item Details</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                {% for bid in bid_list %}
                
                <tr scope="row">
    
                  
                          
                         
                          <td>{{ bid.bidder.username }}</td>
                          <td>
                                {{ bid.item.name }}
                          </td>
                          <td>{{ bid.amount }}$</td>
                          <td>
                                <a href="{% url 'items:bid_detail' bid.id  %}">go to bid</a>
                          </td>
                          <td>
                                <a href="{% url 'items:item_detail' bid.item.id %}">go to item</a>
                          </td>
                
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
    
    
        </div>
    
      </div>

{% endblock content %}