chat/urls.py
from django.urls import path

from .views import index, room

app_name = "chat"

urlpatterns = [
    path("", index, name="index"),
    path("<str:room_name>/", room, name="room"),
]

iss/bids/urls.py
from django.urls import path

from iss.bids import views

app_name = "bids"

urlpatterns = [
    path("list/", views.item_list_view, name="item_list"),
    path("mylist/", views.myitem_list_view, name="item_mylist"),
    path("detail/<str:pk>/", views.item_detail_view, name="item_detail"),
    path("myitemdetail/<str:pk>/", views.myitem_detail_view, name="my_item_detail"),
    path("add/", views.item_create_view, name="item_add"),
    path("update/<str:pk>/", views.item_update_view, name="item_update"),
    path("delete/<str:pk>/", views.item_delete_view, name="item_delete"),
    path("bid_list/<str:pk>/", views.bid_list_view, name="bid_list"),
    path("bid_detail/<str:pk>/", views.bid_detail_view, name="bid_detail"),
    path("bid_add/<str:pk>/", views.bid_create_view, name="bid_add"),
    path("bid_update/<str:pk>/", views.bid_update_view, name="bid_update"),
    path("bid_delete/<str:pk>/", views.bid_delete_view, name="bid_delete"),
]

iss/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("users/", include("iss.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("items/", include("iss.bids.urls", namespace="items")),
    path("chat/", include("iss.chat.urls", namespace="chat")),
]

templates/items/item_delete_confirm.html
{% extends "base.html" %}
{% load static %}

{% block title %}Article {% endblock %}

{% block content %}

    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete {{ object }}. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-link"
                    type="button" value="Cancel"
                    onclick="window.history.go(-1);"/>
                <input class="btn btn-danger" type="submit" value="Confirm"/>
            </form>
        </div>
    </div>

{% endblock content %}

templates/items/item_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Licitatie{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<body>
<br><br><br>


<div class="card">
    <h1>{{item.name}}</h1>
    <hr>
    <h3>Price: {{item.amount}}$</h3>
    <p class="description">Details: <br>{{item.description}}</p>


    <div> <h3>Actions:</h3></div>
    <hr>
    <a class="btn custom-btn" href="{% url 'items:bid_list' item.id  %}" >See current bids for the item</a>
    <hr>
    <a class="btn  custom-btn"href="{% url 'chat:room' item.id  %}">Chat with other bidders</a>
<hr>

 <a class="btn custom-btn" href="{% url 'items:bid_add' item.id  %}" style="background-color: green;">Place a bid</a>
  </div>
</body>
</html>
{% endblock content %}

templates/items/item_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}Item {% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock content %}

templates/items/item_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Licitatie{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
        <body>

                <div class="hero-text-bid">
                        <h1 style="font-size:50px">Available items</h1>
                        
                      </div>
                



<ul class="tilesWrap">
{% for item in item_list %}
<li >
        <h2>{{item.amount}}$</h2>
        <h3 >{{ item.name }}</h3>
        <p>
                <br><br>
        {{item.description|truncatechars:80}}</p>
        <button ><a href="{% url 'items:item_detail' item.id %}">Read more</a></button>
</li>
{% endfor %}
</ul>

<div class="footer">
        <a class="neon-button" href="{% url 'items:item_add' %}"><p>add a new item for sale</p></a>
</div>
{% endblock content %}
</body>
</html>

templates/items/item_myitems.html
{% extends "base.html" %}
{% load static %}

{% block title %}Licitatie{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<body>
<br><br><br>


<div class="card">
    <h1>{{item.name}}</h1>
    <hr>
    <h3>Price: {{item.amount}}$</h3>
    <p class="description">Details: <br>{{item.description}}</p>


    <div> <h3>Actions:</h3></div>
    <hr>
    <a class="btn custom-btn" href="{% url 'items:bid_list' item.id  %}" >See current bids for the item</a>
    <hr>
    <a class="btn  custom-btn"href="{% url 'chat:room' item.id  %}">Chat with other bidders</a>
<hr>

    <a class="btn custom-btn" href="{% url 'items:item_update' item.id  %}">Update item</a>
    <a class ="btn custom-btn"href="{% url 'items:item_delete' item.id  %}" style="background-color: red;">Close auction</a>
    <a class ="btn custom-btn"href="{% url 'items:item_delete' item.id  %}" style="background-color: red;">Delete item</a>
  </div>
</body>
</html>
{% endblock content %}

templates/items/item_mylist.html
{% extends "base.html" %}
{% load static %}

{% block title %}Licitatie{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
        <body>

                <div class="hero-text-bid">
                        <h1 style="font-size:50px">Available items</h1>

                      </div>




<ul class="tilesWrap">
{% for item in item_list %}
<li >
        <h2>{{item.amount}}$</h2>
        <h3 >{{ item.name }}</h3>
        <p>
                <br><br>
        {{item.description|truncatechars:80}}</p>
        <button ><a href="{% url 'items:my_item_detail' item.id %}">Read more</a></button>
</li>
{% endfor %}
</ul>

<div class="footer">
        <a class="neon-button" href="{% url 'items:item_add' %}"><p>add a new item for sale</p></a>
</div>
{% endblock content %}
</body>
</html>